name: CD to Amazon EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: QA-CI # Runner name is QA-CI as have created single runner for CI and CD

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::543808516178:role/github-eks-deploy-role 
        aws-region: ap-south-1

    - name: Setup kubectl config
      run: |
        aws eks update-kubeconfig --name dev-medium-eks-cluster --region ap-south-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/productcatalog/deploy.yaml
        kubectl rollout status deployment/product-catalog
